<?php

/* 
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT DIRECTLY.
 * A file called "autoload.php" will be created in the parent and child themes folder
 * containing an include for all files inside the "/autoload" folder.
 * This file was last generated on 2020-10-15 05:58:30
*/

@ include __DIR__ . '/autoload/basementor-auth.php';
@ include __DIR__ . '/autoload/basementor-database.php';
@ include __DIR__ . '/autoload/basementor-header-simple.php';
@ include __DIR__ . '/autoload/basementor-settings-bootstrap.php';
@ include __DIR__ . '/autoload/basementor-settings-embeds.php';
@ include __DIR__ . '/autoload/basementor-settings-plugins.php';
@ include __DIR__ . '/autoload/basementor-settings-posttype.php';
@ include __DIR__ . '/autoload/basementor-settings-wc-files.php';
@ include __DIR__ . '/autoload/basementor-settings.php';
@ include __DIR__ . '/autoload/basementor-share.php';
@ include __DIR__ . '/autoload/elementor-bootstrap-custom.php';
@ include __DIR__ . '/autoload/elementor-faq.php';
@ include __DIR__ . '/autoload/elementor-list-group.php';
@ include __DIR__ . '/autoload/elementor-nav.php';
@ include __DIR__ . '/autoload/elementor-search-bar.php';
@ include __DIR__ . '/autoload/elementor-section-sticky.php';
@ include __DIR__ . '/autoload/elementor-typeform2.php';
@ include __DIR__ . '/autoload/elementor-woocommerce-cart.php';
@ include __DIR__ . '/autoload/elementor-woocommerce-products.php';
@ include __DIR__ . '/autoload/elementor-woocommerce-search-bar.php';
@ include __DIR__ . '/autoload/hooks.php';
@ include __DIR__ . '/autoload/vue-utils.php';
@ include __DIR__ . '/autoload/vue-wp-editor.php';
@ include __DIR__ . '/autoload/woocommerce-bootstrap-form-field.php';
@ include __DIR__ . '/autoload/woocommerce-checkout-form.php';
@ include __DIR__ . '/autoload/woocommerce-excel.php';
@ include __DIR__ . '/autoload/woocommerce-shipping-calculator.php';
@ include __DIR__ . '/autoload/woocommerce-utils.php';
@ include __DIR__ . '/autoload/wp-helpers.php';
